@DinnerApp.Api_HostAddress = http://localhost:7001

GET {{DinnerApp.Api_HostAddress}}/api/dinners
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI3ZjU0NjljMi0zMjU3LTRlOTItYmMxOS1iMmIwMzM2NWI3YWYiLCJnaXZlbl9uYW1lIjoiS2VuemllIiwiZmFtaWx5X25hbWUiOiJPd2Vucy4gQyIsImp0aSI6Ijg0Yjk2OGQ2LTI2NDAtNDJiOC1hMDUyLThmYzZmZDg3ZjQ2MCIsImV4cCI6MTcwNzc2OTg2NCwiaXNzIjoiT3duYXREaW5uZXIiLCJhdWQiOiJPd25hdERpbm5lciJ9.Gv2w1h5oEltV4yqQjrrF5yclUnqULUvFTAXhLuG42Lc
 