@DinnerApp.Api_HostAddress = http://localhost:7001

GET {{DinnerApp.Api_HostAddress}}/api/dinners
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJiODg4ZDEwOC1iOTdiLTRiZWMtOTZhZi1jODVjOGY1MGQxZjYiLCJnaXZlbl9uYW1lIjoiS2VuemllIiwiZmFtaWx5X25hbWUiOiJPd2Vucy4gQyIsImp0aSI6ImFjMzNiZmJlLTdmZmQtNDM0NC04NDAyLTIxMzhjY2IyYmViYSIsImV4cCI6MTcwNzc2NzcwMywiaXNzIjoiT3duYXREaW5uZXIiLCJhdWQiOiJPd25hdERpbm5lciJ9.WD6pnh2ZDHMXRpj3NGvfK17k4VeLGV54F2m9f_kiJLQeyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJiODg4ZDEwOC1iOTdiLTRiZWMtOTZhZi1jODVjOGY1MGQxZjYiLCJnaXZlbl9uYW1lIjoiS2VuemllIiwiZmFtaWx5X25hbWUiOiJPd2Vucy4gQyIsImp0aSI6ImFjMzNiZmJlLTdmZmQtNDM0NC04NDAyLTIxMzhjY2IyYmViYSIsImV4cCI6MTcwNzc2NzcwMywiaXNzIjoiT3duYXREaW5uZXIiLCJhdWQiOiJPd25hdERpbm5lciJ9.WD6pnh2ZDHMXRpj3NGvfK17k4VeLGV54F2m9f_kiJLQ
 