@DinnerApp.Api_HostAddress = http://localhost:7001
POST {{DinnerApp.Api_HostAddress}}/api/auth/login
Content-Type: application/json

{
  "email": "chilufyao@ownat.com",
  "password": "Kenzie123$"
}
###